project_id = "wzykadjddlkodxbntmza"

[functions.upload-file]
verify_jwt = true

[functions.process-file]
verify_jwt = true

[functions.manage-job]
verify_jwt = true

[functions.export-results]
verify_jwt = true

[functions.linkedin-scraper]
verify_jwt = true

[functions.ai-enhancer]
verify_jwt = true

[functions.proxy-manager]
verify_jwt = true