// This file is automatically generated. Do not edit it directly.
import {createClient} from '@supabase/supabase-js';
import type {Database} from './types';

function databaseConnectionUrl() {
  return "https://wzykadjddlkodxbntmza.supabase.co";
}

const databaseUrl = databaseConnectionUrl();
const SUPABASE_URL = databaseUrl;
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6eWthZGpkZGxrb2R4Ym50bXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNTI3MDAsImV4cCI6MjA2ODcyODcwMH0.V7lnACcsruCUcz82WuxZfV0sYVmeU65JxfvCQhYpDaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});